# Discussão

A análise agregada dos dados no presente estudo aponta que tratamentos avaliados e recomendados pela Conitec possuem maior probabilidade de serem também recomendados por NatJus do que aqueles não avaliados, que, por sua vez, têm maior chance de recomendação pelos NatJus que aqueles avaliados e não recomendados pela Conitec. Futuras pesquisas podem revelar quanto isso decorre da deferência dos NatJus à Conitec ou de endogeneidade, já que tratamentos recomendados pela Conitec tendem a ter evidência mais substancial e, por isso, também têm maior probabilidade de recomendação positiva dos NatJus.

Esse é um achado importante porque mostra alguma convergência entre as avaliações nesses dois sistemas paralelos (e possivelmente concorrentes) de análise de evidência e geração de recomendações. Sem essa correlação, seria ainda mais provável o conflito entre a política pública de saúde e as decisões judiciais. Porém, essa é uma correlação longe de perfeita e nela também se reflete a enorme variação de recomendações entre os NatJus.

Essa variação não pode ser explicada apenas pelo tipo de demanda. As diferenças persistem e são grandes mesmo quando se controla pelas diversas características do tratamento analisado e se compara os mesmos pares medicamento-CID, o que indica diferenças na forma como os NatJus avaliam e recomendam. Se as notas influenciam as decisões, essas diferenças podem criar inequidades dentro da própria judicialização, porque a recomendação que o juiz recebe para um pedido semelhante varia a depender do NatJus que auxilia o tribunal onde a ação foi proposta.

Essas diferenças podem permitir, ainda, o chamado *forum shopping,* quando o litigante escolhe estrategicamente o foro ou o tribunal a depender da probabilidade de sucesso da sua demanda. Mais preocupante ainda são as divergências entre os NatJus locais e o NatJus nacional porque, em tese, um juiz poderia até escolher para qual NatJus mandar, se o nacional ou o local, sabendo qual tem mais probabilidade de emitir recomendação positiva ou negativa.

As divergências podem ter diversas causas. Uma hipótese é a diferença de qualidade. Uma boa avaliação depende de expertise e recursos que podem não estar igualmente distribuídos entre os NatJus. Por exemplo, uma revisão sistemática da literatura pode levar a resultados diferentes de uma incompleta ou enviesada por *cherry-picking,* em que são selecionados apenas artigos que confirmam uma tese inicial. Da mesma forma, uma análise cuidadosa da qualidade e a certeza da evidência por meio de metodologias como o *Grading of Recommendation Assessment, Development and Evaluation* (GRADE) pode levar a resultados diferentes daquela que aceitam acriticamente as conclusões de artigos científicos.

Para além de questões de qualidade, as diferenças entre os NatJus também podem refletir os muitos desacordos sobre interpretação de evidência. Muitas vezes haverá incertezas sobre um tratamento porque as evidências podem ser incompletas, ambíguas ou de qualidade limitada. Por isso, mesmo agências regulatórias e órgãos de ATS podem dar respostas diferentes a depender, por exemplo, do peso que atribuem a comparação indireta ou com placebo [@nicod2012; @tafuri2016], desfechos substitutos [@ciani2021], pesquisas clínicas sem grupo controle ou randomização, evidência de mundo real [@makady2017; @jaksa2025], raridade e severidade de uma doença, a ausência de alternativas, e o que é um benefício clínico "relevante".

Quando há incertezas, diferenças com relação ao grau de exigência da evidência para se recomendar um tratamento podem ser atribuídas a como avaliadores lidam com o trade-off entre falsos negativos (não recomendar tratamentos que beneficiam indivíduos e população) e falsos positivos (recomendar tratamentos que não beneficiam, ou prejudicam, indivíduos e população por razões clínicas ou de custo de oportunidades). Por essa razão, a União Europeia adotou uma ATS comum para a região de forma a evitar a replicação de esforços e reduzir a disparidade no acesso a tratamentos entre seus países membros.

Além de diferenças na análise da evidência clínica, outra causa possível de divergência entre os NatJus é que nem todos usem critérios econômicos como custo-efetividade e impacto orçamentário. A barra para a recomendação de um tratamento sobe bastante quando vai de simplesmente demonstrar que possui vantagem terapêutica para ter que provar que essa vantagem justifica o preço que se cobra por um tratamento e que seu impacto orçamentário é absorvível pelo sistema de saúde sem ameaçar sua eficiência e equidade na distribuição de recursos. Conforme aponta a literatura, nem sempre há uma correlação entre benefício clínico, força da evidência e preço [@vokinger2021; @prasad2017].

Análises econômicas também precisam lidar com incertezas. Os modelos econômicos são construídos em cima de cenários com diferentes projeções quanto a, por exemplo, preço, prevalência da doença e efeitos do tratamento. Existe também variação sobre o critério para se considerar um tratamento custo-efetivo ou com impacto orçamentário aceitável. Esse critério é uma decisão política que reflete os valores de uma sociedade e seus tomadores de decisão, além da capacidade econômica de um país. Por isso, a ATS conjunta da União Europeia limita-se à análise de decisões clínicas, deixando para cada país a avaliação econômica.

Portanto, uma recomendação não é resultado apenas de evidência, mas de visões epistemológicas e valores morais e políticos sobre como recursos escassos devem ser distribuídos [@charlton2023]. Não por acaso, dentro de um mesmo país, as decisões de uma agência regulatória sobre registro de medicamento e a recomendação do órgão de ATS podem divergir [@tafuri2016]. Mesmo dentro de um mesmo órgão de ATS ou agência reguladora pode haver discordâncias entre seus membros [@wranik2021; @tidmarsh2025]. Ademais, recomendações para um mesmo par medicamento-indicação divergem mesmo entre diferentes órgãos de ATS [@kanavos2024; @nicod2012; @allen2017; @akehurst2017; @wangt2018].

Por fim, vale ressaltar o caráter *sui generis* dos NatJus como produtor de recomendações que funciona em paralelo à ATS do sistema de saúde. A recomendação de um NatJus pode mudar a depender de como seus membros enxergam seu papel institucional. Se o NatJus se percebe como tendo um papel subsidiário ao da Conitec, então tenderá a ser deferente à recomendação da Conitec, seja ela positiva ou negativa. Porém, o resultado pode ser diferente se entendem seu papel como um avaliador independente da Conitec ou mesmo como um revisor do trabalho da Conitec.
