# Considerações finais {.unnumbered}

A aposta do STF e do CNJ nos NatJus para lidar com os impactos negativos da judicialização da saúde parte do pressuposto de que eles decorrem de pedidos sem embasamento científico. Portanto, filtrados esses pedidos, restaria a judicialização que promove acesso a demandas legítimas não atendidas pelo SUS. Porém, essa visão acaba ignorando o aspecto distributivo das demandas em saúde.

Demandas podem parecer legítimas quando consideradas as necessidades de cada paciente individualmente. O problema é que há mais demandas legítimas do que recursos para que todas sejam atendidas, e toda escolha envolve impactos distributivos e custos de oportunidade. Órgãos de ATS partem precisamente dessa premissa. Não pressupõem que haja uma resposta certa objetiva, mas que as decisões precisam ser informadas pela melhor evidência; apliquem de forma consistente critérios clínicos e econômicos que sopesem as diferentes necessidades dentro de um sistema de saúde; e sejam feitas por meio de processos que permitam deliberação, participação e controle público.

A grande variação entre as notas técnicas aponta que a aposta nos NatJus para legitimar decisões judiciais por meio da objetividade científica parte de um diagnóstico, no melhor dos casos, incompleto, porque "reduz a questão do fornecimento de tratamentos pelo SUS a um problema de eficácia que pode ser resolvido apenas com evidência científica quando, na verdade, é uma decisão de política pública em que a ciência é apenas um dos fatores a ser considerado" [@wang2018]. A rede NatJus não muda o fato de que judicializar é pulverizar entre juízes e tribunais parte desse poder de decidir quais os critérios utilizados para redistribuir recursos da saúde.

Considerando a enorme variabilidade no entendimento sobre questões clínicas, econômicas e institucionais, os resultados apresentados sobre uma rede tão fragmentada e heterogênea como a do NatJus não surpreendem e podem ser apenas parcialmente resolvidos por mais capacitação ou diretrizes. Porém, vale ressaltar, todo o mais igual, a existência dos NatJus é preferível ao cenário anterior de uma judicialização informada apenas por uma receita médica. As limitações e inconsistências dentro dos NatJus devem apenas reforçar o papel excepcional e residual que a judicialização deve ter na alocação de recursos em saúde.
